AWSTemplateFormatVersion: "2010-09-09"
Description: "Security stack - Security Groups for public EC2 and Application Load Balancer."

Parameters:
  StudentName:
    Type: String
    Default: "Andrey-Felipe-Pinto"
    Description: "Student name used to tag and name resources."

  StudentCode:
    Type: String
    Default: "192177"
    Description: "Student code used to tag resources."

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "Default VPC detected automatically by GitHub Actions."

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "SG-EC2-${StudentName}"
      GroupDescription: !Sub "Public EC2 security group - ${StudentName}"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: "HTTP from internet"
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: "SSH for lab access"
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: "Allow all outbound traffic"
      Tags:
        - Key: Name
          Value: !Sub "SG-EC2-${StudentName}"
        - Key: StudentName
          Value: !Ref StudentName
        - Key: StudentCode
          Value: !Ref StudentCode
        - Key: Project
          Value: "CloudComputingFinal"
        - Key: ManagedBy
          Value: "CloudFormation"

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "SG-ALB-${StudentName}"
      GroupDescription: !Sub "Application Load Balancer security group - ${StudentName}"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: "HTTP from internet"
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: "Allow all outbound traffic"
      Tags:
        - Key: Name
          Value: !Sub "SG-ALB-${StudentName}"
        - Key: StudentName
          Value: !Ref StudentName
        - Key: StudentCode
          Value: !Ref StudentCode
        - Key: Project
          Value: "CloudComputingFinal"
        - Key: ManagedBy
          Value: "CloudFormation"

Outputs:
  EC2SecurityGroupId:
    Description: "EC2 Security Group ID."
    Value: !Ref EC2SecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-EC2SecurityGroupId"

  ALBSecurityGroupId:
    Description: "ALB Security Group ID."
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-ALBSecurityGroupId"
